### PR TITLE
feat: use CGPreflightScreenCaptureAccess API for ScreenAuthStatus

### PR DESCRIPTION
**Pull request by quanglam2807**
Based on this: https://stackoverflow.com/a/65423834/5522263, Apple has an official API to get Screen Auth permission status: `CGPreflightScreenCaptureAccess`: https://developer.apple.com/documentation/coregraphics/3656523-cgpreflightscreencaptureaccess

I've tested this with Electron 11.1.1 + macOS 11 and it worked perfectly.

### CODE REVIEW

**Review by codebytere — CHANGES_REQUESTED** [review]
Hey thanks - this is great. Lint and test CI are failing right now because of missing `LDFLAGS` - when we add CoreGraphics we also need to add that library to [`binding.gyp`](https://github.com/codebytere/node-mac-permissions/blob/59bb8194f7b54aed1cd895e7f1d1fbb4172be846/binding.gyp#L23). 

Once that's fixed up we can get this landed!

**Comment by quanglam2807** [comment]
Thank you, @codebytere. I don't know what happens but CI keeps returning `../permissions.mm:168:9: error: use of undeclared identifier 'CGPreflightScreenCaptureAccess' while `node-gyp` compiles successfully on my local environment.

**Comment by codebytere** [comment]
@quanglam2807 i'll take a closer look soon 🤔

**Comment by mmaietta** [comment]
Any progress made on this?

I'm curious if the CI is running a different version of xcode or using command line tools instead.
Available software in macos node in github workflows:
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md


Maybe the CI SDK version need to be synced with your dev environment @quanglam2807?
A potential way to force a different MacOS SDK via github workflow and to test this hypothesis:
```
env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
```
Ref: https://www.jessesquires.com/blog/2020/01/06/selecting-an-xcode-version-on-github-ci/

**Comment by codebytere** [comment]
@quanglam2807 would you mind rebasing this? I can take it over and try @mmaietta's suggestion above if you'd like as well

**Comment by quanglam2807** [comment]
Thank you for checking this, @codebytere  @mmaietta 

I managed to fix the problem partially by using newer SDK. But I don't know how to fix:
```
dyld: lazy symbol binding failed: Symbol not found: _CGPreflightScreenCaptureAccess
  Referenced from: /Users/runner/work/node-mac-permissions/node-mac-permissions/build/Release/permissions.node
  Expected in: /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
```

This is odd. If the API is supported in macOS 10.15+, then I suppose the symbol must be in the system's framework?

**Comment by codebytere** [comment]
@quanglam2807 looks like: https://github.com/lwouis/alt-tab-macos/issues/704#issuecomment-762852689

**Comment by quanglam2807** [comment]
It seems like the API is added in Bug Sur. So Apple provides wrong documentation? 

I can modify the PR to only use the new API in macOS 11+ and retain the old code for older versions. Would that work?

**Comment by codebytere** [comment]
@quanglam2807 sounds great to me! Thanks for being patient with this PR - appreciated 🙇🏻‍♀️

**Pull request closed without merging**
